# Welcome to Serverless!
#
# For full config options, check the docs:
#    docs.serverless.com

service: starry-sky-service

provider:
  name: aws
  region: ap-southeast-2
  runtime: java8
  profile: personal
  memorySize: 3008

plugins:
 - serverless-apigw-binary

package:
  artifact: target/starry-sky-service-dev.jar

functions:
  getStarrySky:
    handler: com.mycodefu.Handler
    events:
      - http:
          path: sky.png
          method: get

custom:
  apigwBinary:
    types:
      - '*/*'
