# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details

version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u171-jdk

    working_directory: ~/stars

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn package

      - persist_to_workspace:
          root: ~/stars
          paths:
            - '*'

  deploy:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/starbuild
    steps:
      - attach_workspace:
          at: /tmp/stars

      - run:
          name: Move code from attached workspace
          command: mv /tmp/stars/* .

      - run: ls

      - restore_cache:
          keys:
          - serverless-dependency

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: serverless-dependency

      - run:
          name: Deploy API to AWS
          command: |
            ./node_modules/.bin/sls deploy

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
